### ISSUE TITLE
The "%" operator.

### ISSUE THREAD

**Issue by xeoncross** [runekaagaard/snowscript#1]
> Strings can be concatenated using the "%" operator.

This is a terrible idea. The period is much, much, much easier to type and string concatenation is very common in code. I also recommend you take a closer look at CoffeeScript for some improvements to the syntax.

**Comment by runekaagaard** [comment]
Hi

Thank you very much for your comment!

Actually it's a great idea :) Joke aside, idiomatic string concatenation in Snowscript will be something like:

```
"I am a {var} together with a {function_call()}"
```

Not so much:

```
"I am a " % var %  " together with a " % function_call()
```

I had to edit that last example three times to get the space right :) At least on a danish keyboard it's really easy to type %. %%%%%%%%%%%%.

The reason I changed the meaning of the "." operator was that I wanted to use it to access object properties as in:

```
my_instance.my_method()
```

I did study CoffeeScript as well as other languages pretty closely. Anything specific you have in mind? Snowscript could really use contributors, interested?
