### ISSUE TITLE
Switch as an expression

### ISSUE THREAD

**Issue by vendethiel** [runekaagaard/snowscript#12]
i.e.

```
location = switch blah
 ...
```

(I'm not even sure `switch` is here tbh :p)

**Comment by runekaagaard** [comment]
There's no switch :)

**Comment by jasperkennis** [comment]
Now hold on, but should there be switch?

**Comment by runekaagaard** [comment]
There will be no switch :) Actually there was, but I removed it again. This PEP is interesting: http://www.python.org/dev/peps/pep-3103/ .

**Comment by vendethiel** [comment]
C'mon, you can do better than python ;)
