### ISSUE TITLE
mod keyword error.

### ISSUE THREAD

**Issue by waterlink** [runekaagaard/snowscript#15]
When using something like:

```
class A
    extends StandardController

    fn index
        .load.model('HelloModel', 'hello')
        .hello.say_hi('john')
```

I have an error in `.load.model()` line. Snowscript parses 'mod' and translates it to %, so we have a syntax error in php here:

```
$this->load->%el('HelloModel', 'hello');
```

Seems to be that regex for mod should be changed from `mod` to `\\bmod\\b`

**Comment by waterlink** [comment]
Proposed diff to work:

```
diff --git a/src/python/snow/lexer/tokens.py b/src/python/snow/lexer/tokens.py
index 7a33045..3b457fc 100644
--- a/src/python/snow/lexer/tokens.py
+++ b/src/python/snow/lexer/tokens.py
@@ -165,7 +165,7 @@ def t_MOD_EQUAL(t):


 def t_MOD(t):
-    r'mod'
+    r'\bmod\b'
     t.type = RESERVED.get(t.value, "MOD")
     return t
```

**Comment by runekaagaard** [comment]
Hi. The entire `t_MOD`function could be removed, because "MOD" is already in the `tokens`list. THANKS for the bug report, AND the fix, which works too!
