### ISSUE TITLE
compiling and testing

### ISSUE THREAD

**Issue by francescoagati** [runekaagaard/snowscript#2]
Hi,
how can i compile for try some code, and how running the test for help you?

Thanks

**Comment by runekaagaard** [comment]
Dear Francesco

Thanks a lot for taking an interest in Snowscript!

1) Running the tests.

cd to tests and run
    pear run-tests -r

This should be stated in a README in the tests folder. I just broke some
of the class tests, so about 44 out of 58 should pass. PHPT generates nices
.diff, .out, etc. for broken tests.

2) Compile code.

At the moment the only way to compile snowcode to PHP is to write a
test for it :)

One of the things on the roadmap is to create a compiler script. See
the "snowscript_to_php"
function at https://github.com/runekaagaard/snowscript/blob/master/tests/bootstrap_tests.php

3) Helping out

That would be so great. If you think it could be fun to hack on
Snowscript, I could start to
document and clean up some things, to make it easier to understand for
a new set of eyes.
And of course I can (try) to answer any questions you might have.

**Comment by francescoagati** [comment]
Thanks in advance i am happy on can help you

**Comment by runekaagaard** [comment]
Adding README for tests here: https://github.com/runekaagaard/snowscript/blob/master/tests/README.rst
