### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by ualinker** [runekaagaard/snowscript#6]
I saw that CLI compiler tool still listed in TODO, but how do you use it right now? How do you compile .snow files? It would be nice to see that documented.

**Comment by fedesilvaponte** [comment]
I agree with ualinker, I like this project, but can't find any information on how to use it.

**Comment by runekaagaard** [comment]
Hi ualinker and fedesilvaponte

Up until now I havent actually compiled .snow files and simply been running tests as in [here](https://github.com/runekaagaard/snowscript/blob/master/tests/stmt/ternary.phpt). But given the introduction of the first actual [.snow](https://github.com/runekaagaard/snowscript/blob/master/src/php/Snowscript/Lexer.snow) file I've found myself wanting too.

At 236ac1700b53032c157c1e521871cb38aad8230a I've added two very unfinished compile scripts and very unfinished [usage documentation](https://github.com/runekaagaard/snowscript/blob/master/USAGE.rst).

Please bear in mind everything is prealpha quality and that the error messages lack linenumber and position.
