### ISSUE TITLE
Watchdog too should be a requirement

### ISSUE THREAD

**Issue by jasperkennis** [runekaagaard/snowscript#9]
The watch command throws errors without watchdog installed.

**Comment by jasperkennis** [comment]
Sorry fiddled with the pull request.

**Comment by runekaagaard** [comment]
Thanks for that! And congratulations in becoming the Second person in the universe to actually compile Snowscript into PHP :)

**Comment by vendethiel** [comment]
(am still looking for a way to have easy_install and pear working on windows)

**Comment by jasperkennis** [comment]
[Well to say either of us was first or second in the UNIVERSE is kind of an assumption](http://www.quotationspage.com/quote/33085.html), but that aside I'm happy to know that I was the second within a radius of at least a couple a hundred lightyears, and also I hope I'll be able to support your amazing project some more! Not working in windows though.

**Comment by vonj** [comment]
Haha, you guys rock.

**Comment by runekaagaard** [comment]
LOL

@jasperkennis @Nami-Doc: No it's not working on Windows yet. Added #11.
